---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

modules:
  - type: os-release
    properties:
      NAME: Fedora Linux
      PRETTY_NAME: Fedora Linux 43 (Kinoite - Custom BlueBuild)
      BUILD_ID: 2026-02-17.3e

  - type: files
    files:

      - source: base-root
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: rpmfusion

      files:
        - https://download.opensuse.org/download/repositories/home:/mkittler/Fedora_%OS_VERSION%/home:mkittler.repo
        - https://download.opensuse.org/download/repositories/home:/paul4us/Fedora_%OS_VERSION%/home:paul4us.repo

      # copr:
      #  -

    install:
      packages:
        - gcc
        - python
        - fish
        - git
        - klassy

      # sync
        - syncthing
        - syncthingctl-qt6
        - syncthingfileitemaction-qt6
        - syncthingtray-qt6
        - syncthingplasmoid-qt6

      # filesystem and backup
        - btrfsmaintenance
        - btrfs-progs
        - btrfs-assistant
        - btrbk
        - trash-cli

      # network
        - tailscale
        - cockpit
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-files
        - cockpit-storaged

      # codecs
        - gstreamer1-plugin-dav1d
        - gstreamer1-plugin-libav
        - gstreamer1-plugin-openh264
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-bad-free-extras
        - gstreamer1-plugins-bad-free-fluidsynth
        - gstreamer1-plugins-bad-free-libs
        - gstreamer1-plugins-bad-free-lv2
        - gstreamer1-plugins-bad-free-opencv
        - gstreamer1-plugins-bad-free-wildmidi
        - gstreamer1-plugins-bad-free-zbar
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-base
        - gstreamer1-plugins-good
        - gstreamer1-plugins-good-extras
        - gstreamer1-plugins-good-gtk
        - gstreamer1-plugins-good-qt
        - gstreamer1-plugins-good-qt6
        - gstreamer1-plugins-ugly-free
        - lame
        - lame-libs

      # build packagekit-bootc
        - PackageKit-devel
        - meson
        - ninja-build
        - glib2-devel

    replace:
      - from-repo: rpmfusion-free
        packages:
          - ffmpeg
          - ffmpeg-libs
          - libva
          - libva-utils
          - mesa-dri-drivers
          - mesa-vulkan-drivers
          - vulkan-loader
          - mesa-libGLU


    remove:
      auto-remove: true
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - ffmpeg-free
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default

        install: # system flatpaks we want all users to have and not remove

        # web
          - app.zen_browser.zen

        # network
          - com.protonvpn.www

        # media
          - org.videolan.VLC
          - org.kde.gwenview

        # office
          - org.kde.kate
          - org.libreoffice.LibreOffice
          - md.obsidian.Obsidian
          - org.kde.okular

        remove:
          - org.mozilla.firefox

      - scope: user # Also add Flathub user repo, but no user packages

  - type: script
    scripts:
      - base-add-fstab-extras.sh
      - base-build-packagekit-bootc.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
