---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: rpmfusion

      files:
        - https://download.opensuse.org/download/repositories/home:/mkittler/Fedora_%OS_VERSION%/home:mkittler.repo
        - https://download.opensuse.org/download/repositories/home:/paul4us/Fedora_%OS_VERSION%/home:paul4us.repo

      # copr:
      #  -

    install:
      packages:
        - python
        - fish
        - git
        - klassy

        # sync
        - syncthing
        - syncthingctl-qt6
        - syncthingfileitemaction-qt6
        - syncthingtray-qt6
        - syncthingplasmoid-qt6

        # filesystem and backup
        - btrfs-assistant
        - btrbk

        # network
        - tailscale

        # codecs
        - ffmpeg
        - ffmpeg-libs
        - libva
        - libva-utils
        - mesa-dri-drivers
        - mesa-vulkan-drivers
        - vulkan-loader
        - mesa-libGLU
        - gstreamer1-plugins-{bad-\*,good-\*,base}
        - gstreamer1-plugin-openh264
        - gstreamer1-libav
        - lame\*

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - gstreamer1-plugins-bad-free-devel
        - ffmpeg-free
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default

        install: # system flatpaks we want all users to have and not remove

        # web
          - app.zen_browser.zen

        # network
          - com.protonvpn.www

        # media
          - org.videolan.VLC
          - org.kde.gwenview

        # office
          - org.libreoffice.LibreOffice
          - md.obsidian.Obsidian
          - org.kde.okular

        remove:
          - org.mozilla.firefox

      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
