---
# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json

modules:
  - type: os-release
    properties:
      PRETTY_NAME: Fedora Kinoite (BlueBuild)
      BUILD_ID: '11c'

  - type: files
    files:
      - source: base-root
        destination: /

  - type: dnf
    repos:
      nonfree: rpmfusion
      files:
        - https://download.opensuse.org/download/repositories/home:/mkittler/Fedora_%OS_VERSION%/home:mkittler.repo # for syncthingtray
        - https://download.opensuse.org/download/repositories/home:/paulmcauley/Fedora_%OS_VERSION%/home:paulmcauley.repo # for klassy

    install:
      packages:
        - perf
        # - gcc
        - python
        - python-launcher
        - python3-pip
        - fish
        - git
        - monitor-edid
        - setroubleshoot
        - yt-dlp
        
      # kde additions
        - klassy # this requires the paul4us repo
        - kcron
        - oxygen-sounds

      # sync
        - syncthing
        - syncthingctl-qt6 # these require the mkittler repo
        - syncthingfileitemaction-qt6
        #- syncthingtray-qt6
        - syncthingplasmoid-qt6

      # filesystem and backup
        - python3-btrfs
        - btrfsmaintenance
        - btrfs-progs
        - btrfs-assistant
        - duperemove
        - btrbk

        - hdparm
        - hd-idle
        - fatrace
        - iotop-c
        - ncdu
        - trash-cli

      # network
        - tailscale
        - cockpit
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-files
        - cockpit-storaged

      # codecs
        - gstreamer1-plugin-dav1d
        - gstreamer1-plugin-libav
        - gstreamer1-plugin-openh264
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-bad-free-extras
        - gstreamer1-plugins-bad-free-fluidsynth
        - gstreamer1-plugins-bad-free-libs
        - gstreamer1-plugins-bad-free-lv2
        - gstreamer1-plugins-bad-free-opencv
        - gstreamer1-plugins-bad-free-wildmidi
        - gstreamer1-plugins-bad-free-zbar
        - gstreamer1-plugins-bad-freeworld
        - gstreamer1-plugins-base
        - gstreamer1-plugins-good
        - gstreamer1-plugins-good-extras
        - gstreamer1-plugins-good-gtk
        - gstreamer1-plugins-good-qt
        - gstreamer1-plugins-good-qt6
        - gstreamer1-plugins-ugly-free
        - lame
        - lame-libs
        - openh264

      # build packagekit-bootc
      #   - PackageKit-devel
      #   - meson
      #   - ninja-build
      #   - glib2-devel

    replace:
      - from-repo: rpmfusion-free
        allow-erasing: true
        packages:
          - old: ffmpeg-free
            new: ffmpeg
          - vvenc-libs
          - libheif
          - glycin-loaders
          - glycin-libs
          - ffmpeg-libs
          - libva
          #- libva-utils
          - mesa-dri-drivers
          - mesa-vulkan-drivers
          - vulkan-loader
          - mesa-libGLU
          - x264-libs
          - x265-libs
      - from-repo: rpmfusion-nonfree
        allow-erasing: true
        packages:
          - old: libfdk-aac
            new: fdk-aac

    remove:
      auto-remove: true
      packages:
        - fcitx5
        - fcitx5-*
        - pipewire-config-raop # might consider unblocking this at some point but it gets on my nerves
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system # (default repo is Flathub)

        install:
        # themes
          - org.gtk.Gtk3theme.Breeze
          - org.gtk.Gtk3theme.Breeze-Dark

        # utils
          - io.github.jonmagon.kdiskmark

        # web
          - app.zen_browser.zen

        # network
          - com.protonvpn.www

        # media
          - org.videolan.VLC
          - org.kde.gwenview

        # office
          - org.kde.kate
          - org.libreoffice.LibreOffice
          - md.obsidian.Obsidian
          - org.kde.okular

        remove:
          - org.mozilla.firefox

      # - notify: false
      #   scope: user
      # I don't actually want a flatpak user repo
      # maybe this is controversial but I don't like program data in /home and my devices only ever have one user anyway

  - type: script
    snippets:
      - "sudo plymouth-set-default-theme better-bgrt-mac-style" # apply the custom plymouth theme loaded into /usr/share/plymouth/themes earlier
      - "echo 'ShowBuild=true' | sudo tee -a /etc/xdg/kcm-about-distrorc" # show the build ID in KDE info centre - it's useful to see both the upstream image and personal build versions

    # scripts:
      # - base-build-packagekit-bootc.sh

  - type: systemd
    system:
      enabled:
        - tailscaled.service

  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
